<?php

namespace FormArmorBundle\Repository;

/**
 * plan_formationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class plan_formationRepository extends \Doctrine\ORM\EntityRepository
{
}
